# Generated by Django 4.2.7 on 2026-05-04 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0008_postawareness_is_anonymous_postcomplain_is_anonymous_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('post_id', models.PositiveIntegerField()),
                ('message', models.TextField()),
                ('new_status', models.CharField(max_length=20)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Feedback',
                'verbose_name_plural': 'Staff Feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='emailqueue',
            name='user',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='idea',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='question',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='idea',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='postawareness',
            options={'ordering': ['-created_at'], 'verbose_name': 'Awareness Post', 'verbose_name_plural': 'Awareness Posts'},
        ),
        migrations.AlterModelOptions(
            name='postcomplain',
            options={'ordering': ['-created_at'], 'verbose_name': 'Complaint', 'verbose_name_plural': 'Complaints'},
        ),
        migrations.AlterModelOptions(
            name='postemergency',
            options={'ordering': ['-created_at'], 'verbose_name': 'Emergency Post', 'verbose_name_plural': 'Emergency Posts'},
        ),
        migrations.AlterModelOptions(
            name='postinnovation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Innovation Post', 'verbose_name_plural': 'Innovation Posts'},
        ),
        migrations.AlterModelOptions(
            name='postothers',
            options={'ordering': ['-created_at'], 'verbose_name': 'Other Post', 'verbose_name_plural': 'Other Posts'},
        ),
        migrations.AlterModelOptions(
            name='postrecommendations',
            options={'ordering': ['-created_at'], 'verbose_name': 'Recommendation', 'verbose_name_plural': 'Recommendations'},
        ),
        migrations.AlterModelOptions(
            name='postsuggestions',
            options={'ordering': ['-created_at'], 'verbose_name': 'Suggestion', 'verbose_name_plural': 'Suggestions'},
        ),
        migrations.AlterModelOptions(
            name='reporting',
            options={'ordering': ['-created_at'], 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.RenameField(
            model_name='idea',
            old_name='creation_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='category',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='description',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='status',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='user',
        ),
        migrations.AddField(
            model_name='postawareness',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='postawareness',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='postcomplain',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='postcomplain',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='postemergency',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='postemergency',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='postinnovation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='postinnovation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='postothers',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='postothers',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='postrecommendations',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='postrecommendations',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='postsuggestions',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='postsuggestions',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reporting',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='reporting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='postawareness',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='postcomplain',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='postemergency',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='postinnovation',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='postothers',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='postrecommendations',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='postsuggestions',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='report_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='school',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='telephone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('regular_user', 'Regular User'), ('staff', 'Staff'), ('admin', 'Admin')], default='regular_user', max_length=20),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='EmailQueue',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
